name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    - run: make test
    - run: make verify

  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ./actions/install-slsactl
    - run: make e2e

  test-verify-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: ./actions/verify
      with:
        image: ghcr.io/kubewarden/policy-server:v1.19.0
